#!/usr/bin/env perl
use strict;
use warnings;
use 5.024001;

use FindBin qw< $Bin >;
BEGIN { unshift @INC, "$Bin/../lib", "$Bin/../local/lib/perl5" }
use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('WebService::Ordeal');
